### ISSUE TITLE
How to repro screenshots?

### ISSUE THREAD

**Issue by OR13** [kengz/CGKB#1]
I'm new to neo4j how do I get that screenshot example?

```
$ npm run server # works
$ npm start # does nothing (but export the module)
$ npm test # test passes
```

I've been hunting for more services like this if you have any similar projects to share, I would greatly appreciate the info.

Happy to answer any questions about Intent Recognizers / Entity Extraction with  MS Bot Service, API.AI

**Comment by kengz** [comment]
Hey, this is only the server and backend implementation. To actually query it you need the interface [AIVA](https://github.com/kengz/aiva). Setup should be quick given the binary u can use, see [here](https://github.com/kengz/aiva#setup). The fastest way by far is Slack or Telegram - just get bot token from them.

Quite some people have had successes getting those to work, plus what's shown in the screenshot. Some debugging info we went through can be found in that repo's Issues section.

Not sure if you found this repo from an article, but [here's it with the full tutorial](https://explosion.ai/blog/chatbot-node-js-spacy).

**Comment by OR13** [comment]
thanks! This is super helpful.
